### PR TITLE
support for native debug symbols

### PR DESCRIPTION
**Pull request by newnon**

### CODE REVIEW

**Comment by Vacxe** [comment]
@newnon  I terribly sorry for late replay mate! Honestly was pretty suprised that this repo will be used so much ;) As well your changes required rebase. I will cherry-pick those changes into new release and prepare it tomorrow.

**Comment by newnon** [comment]
here is 4 differents problems
wrong mime type for bundles
support for native debug sumbols
added flag for  changesNotSentForReview 
and fix docker file right without it on some systems you cant run it

**Comment by newnon** [comment]
Confict resolved

**Comment by Vacxe** [comment]
@newnon thanks for update mate. I just have a few comments:

1. First of all happy to merge Docker update + Code deobfuscations
2. About custom flag for `changesNotSentForReview`. Here is some fundamental conflict with Idea of this library. It should provide a Pure and Transparent CLI over Google Java library implementation, but adding `changesNotSentForReview` with default parameter to particular request looks not clear. I added more massive changes to support your request https://github.com/Vacxe/google-play-cli-kt/pull/22 Please take a look. This implementation will provide parameters for all available requests to avoid scalability issues in future.
3. Bundle support was merged https://github.com/Vacxe/google-play-cli-kt/pull/21 

---

As an extra comment I saw in you previous PR that you renamed `apk` to `bundle` for Bundle class, happy to merge it as well. 
Waiting for your PR review for #22 and then I can create a new release

**Comment by Vacxe** [comment]
As well: https://github.com/Vacxe/google-play-cli-kt/pull/24/

I cherry-picker your commit to this PR and modified to use a release binary to improve a transparency

**Comment by Vacxe** [comment]
f4f6cd4bb34026d1cde9f740cca0ee2e394c8283 was merged to main

**Comment by Vacxe** [comment]
Few comments from this PR was cherry-picked into main

**Pull request closed without merging**
